### ISSUE TITLE
[Feature request] Support IPMI actions

### ISSUE THREAD

**Issue by iMikeG6** [ShaneMcC/PXE-Manager#159]
Hello @ShaneMcC, thanks for this awesome project which i really like. I was used to Foreman but even though I really enjoy working with it, it's way to heavy for use just as a kickstart generator.

So I'm considering using pxe-manager, which is nice and pretty easy to use for simple uses cases, though, I think some improvements would benefit the community.

In Foreman, you can add to servers, IPMI addresses which can be used for powering, restarting, set boot to pxe, etc, any server that has IPMI enabled. Would you considering adding such feature in pxe-manager ?

**Comment by ShaneMcC** [comment]
At this time I do not intend to implement this.

I can see some value in it, so I may revisit this decision in future, but it's not something I currently require (my primary use case is provisioning virtual machines rather than hardware machines)

In addition, I would want to consider how best to support this for maximum compatibility and flexibility. (ie is it just ultimately shelling out to `ipmitool`, do I want to support powering on/off PDUs, should it show current status etc.)

Ultimately if this was to be implemented, I'd want something similar to the plugable auth stuff - so different classes that implement the different methods (eg `ipmitool`, `pdureset` etc).

The classes would need to define what parameters they require (eg ip, username, password, portnumber) and what actions are available (`reboot`, `enable pxe boot` etc).

Then the edit server page would have a dropdown to select an `oob type`  or something and dynamically show the required fields and the view page would need to show any buttons related to the currently selected type.
