### ISSUE TITLE
[Feature request] Add global variables support and password type

### ISSUE THREAD

**Issue by iMikeG6** [ShaneMcC/PXE-Manager#160]
Hello @ShaneMcC, thanks for this awesome project which i really like. I was used to Foreman but even though I really enjoy working with it, it's way to heavy for use just as a kickstart generator.

So I'm considering using pxe-manager, which is nice and pretty easy to use for simple uses cases, though, I think some improvements would benefit the community.

It'll be really nice if custom global variables could be added to pxe-manger.
Being able to create a global variable which can then be used in different image templates or servers without the need of recreating it every time in each template will be very useful.

Also, if you can add password type in normal variables definitions, that would be great, especially for password entries.
And speaking of password, at least for kickstart, it'll be great to have a input where you enter clear password and it'll then be encrypted for kickstart file instead of doing it manually in the terminal with `openssl passwd -6`

**Comment by ShaneMcC** [comment]
I've added password fields now, though it's important to remember that anyone can still just look at the generated output either directly, or via the preview page and see the passwords, and sometimes browser/password-manager autofill can get a bit over-zealous when it sees a password field.

As for global variables, I'm not going to add these.

You can use template inheritance to do this - if you define an image with the variables you want and no data in the pxedata/kickstart/postinstall section, you can then add `{% use '999/pxedata' %}` to any of your templates that you want to use the variables in (where `999` is the id of your global variables template).

This will then import the variables when editing servers - but won't otherwise change your pxedata as the template has nothing to actually import.
