### ISSUE TITLE
Importable/Exportable images

### ISSUE THREAD

**Issue by dominicbr** [ShaneMcC/PXE-Manager#90]
It would be super handy if there were support for importing/exporting image configuration though the web UI.

Bonus points if you support bulk export/import and the ability to import from a URL (ie I give it a pastebin URL and it imports from that).  

Thanks!

**Comment by ShaneMcC** [comment]
Bulk seems more annoying

Mainly because of:
 - what to do if importing 1 of them fails, abort all? abort just that one?
 - what about extended images - should the bulk export include the image IDs and then the bulk import automatically change them?

Importing with extends is already gonna be interesting, as it may fail to import if the extends ID isn't there, or it may import wrong if the IDs don't match
(import "wrong" in that it will import fine, but the resulting image may not do the same thing)

**Comment by ShaneMcC** [comment]
Basic import/export exist for images.

At this time, probably not going to do bulk import/export (for reasons mentioned above) or import-from-url.
